events {
    worker_connections 1024;
}

http {
    # Nginx-Versionsnummer im Server-Header verbergen
    server_tokens off;

    # Maximum Body Size (Schutz vor zu großen File-Uploads)
    client_max_body_size 10M;

    # Timeouts gegen Slowloris-Angriffe
    client_body_timeout 10s;
    client_header_timeout 10s;
    keepalive_timeout 65s;
    send_timeout 10s;

    # Erstellt eine 10MB Zone ("req_limit_zone") für IP-Adressen ($binary_remote_addr).
    # Erlaubt maximal 10 Anfragen pro Sekunde (10r/s) pro IP.
    limit_req_zone $binary_remote_addr zone=req_limit_zone:10m rate=10r/s;
    limit_req_status 429; # Sendet HTTP 429 (Too Many Requests) bei Überschreitung

    server {
        listen 80;
        server_name ${domain};
        return 301 https://$host$request_uri;
    }

    server {    
        listen 443 ssl;
        server_name ${domain};
        ssl_certificate     /etc/letsencrypt/live/${domain}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_session_cache shared:SSL:1m;

        location / {
            limit_req zone=req_limit_zone burst=20 nodelay;
            proxy_pass http://server:80;

            # Den normalen Host-Header setzen
            proxy_set_header Host $host;
            # 2X-Forwarded-Header rigoros überschreiben (Schutz vor Spoofing!)
            # Wir nutzen $remote_addr statt $proxy_add_x_forwarded_for, um Client-Fakes komplett zu löschen
            proxy_set_header X-Forwarded-For $remote_addr;

            # Protokoll überschreiben (http / https)
            proxy_set_header X-Forwarded-Proto $scheme;

            # Host überschreiben, falls der Client einen X-Forwarded-Host mitsendet
            proxy_set_header X-Forwarded-Host $host;

            # (Optional, aber gut) Echte IP für andere Zwecke bereithalten
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}